### PR TITLE
add folder Logo

### PR DESCRIPTION
**Pull request by trinhminhhieu**
Hello
Here are the logo folders for your reference,
If you need to edit the code, please approve the membership

### CODE REVIEW

**Comment by jibin2706** [comment]
It doesn't meet expectation. Needs come creativity.

**Comment by trinhminhhieu** [comment]
Do you need me to revise the code?

**Comment by trinhminhhieu** [comment]
Are you using react, node, express?

**Comment by jibin2706** [comment]
The logo design looks very basic.
The project uses gatsby.

**Pull request closed without merging**
